### ISSUE TITLE
Feature Request:  support arm64

### ISSUE THREAD

**Issue by johnwmail** [karellen/karellen-sysbox#2]
As title, please consider support arm64 as well, thank you.

**Comment by arcivanov** [comment]
I would love to, but I have no machine on which to test it and QEMU generally sucks for emulation. Let me see if I can enable them.

**Comment by arcivanov** [comment]
@johnwmail I have enabled aarch64 builds, they seem to have succeeded. Please let me know if they work for you.

**Comment by johnwmail** [comment]
@arcivanov Thank you.
Yes, It works for me, thanks.

![image](https://github.com/user-attachments/assets/66c085a5-f737-46d8-97a3-3ae983b831fc)
